name: faultSeg36
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.3.4=py36h5ca1d4c_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py36_0
  - numpy=1.19.1=py36hbc911f0_0
  - numpy-base=1.19.1=py36hfa32c7d_0
  - opencv=4.5.0=py36_2
  - pandas=1.1.4=py36hd87012b_0
  - pip=20.2.4=py_0
  - py-opencv=4.5.0=py36hac0dd68_2
  - python=3.6.11=h4d41432_2_cpython
  - pip:
    - imageio==2.9.0
    - matplotlib==3.3.2
    - pillow==8.0.1
    - scikit-image==0.17.2
